---
kind: pipeline
name: Build&Push image

trigger:
  branch:
  - master
  event:
  - push
  - custom

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: komakio/website
    tags: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}

- name: git deploy
  image: bitnami/git
  commands:
  - git clone "https://$(echo $githubUsername):$(echo $githubPassword)@github.com/wikibusiness/komak-k8s.git"
  - cd komak-k8s
  - rm -f src/website-version.yaml
  - rm -f src/website-production-version.yaml
  - "echo 'imageTag: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}' > src/website-version.yaml"
  - "echo 'imageTag: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}' > src/website-production-version.yaml"
  - "git add . && git commit -a -m 'Updated website to tag ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}' && git push"

  environment:
    githubUsername:
      from_secret: GITHUB_USERNAME
    githubPassword:
      from_secret: GITHUB_PASSWORD

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: errors
  when:
    status: [ failure ]
---
kind: pipeline
name: Build&Push image to staging

trigger:
  branch:
    include:
    - "*"
    exclude:
    - master
  event:
  - push

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: komakio/website
    tags: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}

- name: git deploy
  image: bitnami/git:2.26.2
  commands:
  - git clone "https://$(echo $githubUsername):$(echo $githubPassword)@github.com/wikibusiness/komak-k8s.git"
  - cd komak-k8s
  - rm -f src/website-version.yaml
  - "echo 'imageTag: ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}' > src/website-version.yaml"
  - "git add . && git commit -a -m 'Updated website to tag ${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}' && git push"

  environment:
    githubUsername:
      from_secret: GITHUB_USERNAME
    githubPassword:
      from_secret: GITHUB_PASSWORD
---
kind: signature
hmac: 20696fbe47889615b126c49ebe064f8b7d2b0d7c811feac94fe957061fec2384

...
